name: API CI

on:
  push:
    paths: ["questions-generator-api/**"]
  pull_request:
    paths: ["questions-generator-api/**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: questions-generator-api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - run: npm test
